More improvements to kafka_lag check

diff --git a/templates/plugins/check_kafka_lag b/templates/plugins/check_kafka_lag
--- a/templates/plugins/check_kafka_lag
+++ b/templates/plugins/check_kafka_lag
@@ -8,13 +8,22 @@
 # triggers alarm if lag was detected on any of the topics.
 #
 
+set -eo pipefail
+
 PROGNAME=$(basename $0)
 PROGPATH=$(echo $0 | sed -e 's,[\\/][^\\/][^\\/]*$,,')
 
 . $PROGPATH/utils.sh
 
+fail() {
+  local msg="$@"
+  echo $msg 1>&2
+  exit ${STATE_UNKNOWN}
+}
+
 # Default variables
-KAFKACMD='/bin/kafka-consumer-groups'
+KAFKACMD=$(which kafka-consumer-groups 2>/dev/null || \
+  fail "Required kafka-consumer-groups command not found.")
 WARN=10000
 CRIT=30000
 
@@ -34,13 +43,6 @@ usage() {
   echo -e "\t-w <warning>\twarning threshold (offset lag, default: 10000)"
   echo -e "\t-c <critical>\tcritical threshold (offset lag, default: 30000)"
   echo -e "\t-h\t\tDisplay this help message"
-  exit ${STATE_UNKNOWN}
-}
-
-# Prints give message and exit with proper code
-fail() {
-  local msg="$@"
-  echo $msg 1>&2
   exit ${STATE_UNKNOWN}
 }
 
@@ -80,8 +82,10 @@ check_arguments() {
              ;;
       esac
   done
-  [ -z ${group} ] && usage
-  [ -z ${bootstrap} ] && usage
+  if [ -z ${group} ] || [ -z ${bootstrap} ]
+  then
+    usage
+  fi
 }
 
 # Main function
